var league = [
  {champId : "1", name : "Aatrox", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "2", name : "Ahri", "primaryRole": "mage", "secondaryRole": "assassin", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "3", name : "Akali", "primaryRole": "assassin", "secondaryRole": null, "primaryPosition" : "middle", "secondaryPosition" : "top"},
  {champId : "4", name : "Alistar", "primaryRole": "tank", "secondaryRole": "support", "primaryPosition" : "support", "secondaryPosition" : "jungle"},
  {champId : "5", name : "Amumu", "primaryRole": "tank", "secondaryRole": "mage", "primaryPosition" : "jungle", "secondaryPosition" : "support"},
  {champId : "6", name : "Anivia", "primaryRole": "mage", "secondaryRole": "support", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "7", name : "Annie", "primaryRole": "mage", "secondaryRole": null, "primaryPosition" : "middle", "secondaryPosition" : "support"},
  {champId : "8", name : "Ashe", "primaryRole": "marksman", "secondaryRole": "support", "primaryPosition" : "bottom", "secondaryPosition" : null},
  {champId : "9", name : "Azir", "primaryRole": "mage", "secondaryRole": "marksman", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "10", name : "Bard", "primaryRole": "support", "secondaryRole": "mage", "primaryPosition" : "support", "secondaryPosition" : null},
  {champId : "11", name : "Blitzcrank", "primaryRole": "tank", "secondaryRole": "fighter", "primaryPosition" : "support", "secondaryPosition" : null},
  {champId : "12", name : "Brand", "primaryRole": "mage", "secondaryRole": null, "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "13", name : "Braum", "primaryRole": "support", "secondaryRole": "tank", "primaryPosition" : "support", "secondaryPosition" : "top"},
  {champId : "14", name : "Caitlyn", "primaryRole": "marksman", "secondaryRole": null, "primaryPosition" : "bottom", "secondaryPosition" : null},
  {champId : "15", name : "Cassiopeia", "primaryRole": "mage", "secondaryRole": null, "primaryPosition" : "middle", "secondaryPosition" : "top"},
  {champId : "16", name : "ChoGath", "primaryRole": "tank", "secondaryRole": "mage", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "17", name : "Corki", "primaryRole": "marksman", "secondaryRole": null, "primaryPosition" : "bottom", "secondaryPosition" : "middle"},
  {champId : "18", name : "Darius", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "19", name : "Diana", "primaryRole": "fighter", "secondaryRole": "mage", "primaryPosition" : "middle", "secondaryPosition" : "top"},
  {champId : "20", name : "DrMundo", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "21", name : "Draven", "primaryRole": "marksman", "secondaryRole": null, "primaryPosition" : "bottom", "secondaryPosition" : null},
  {champId : "22", name : "Ekko", "primaryRole": "assassin", "secondaryRole": "fighter", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "23", name : "Elise", "primaryRole": "mage", "secondaryRole": "fighter", "primaryPosition" : "middle", "secondaryPosition" : "jungle"},
  {champId : "24", name : "Evelynn", "primaryRole": "assassin", "secondaryRole": "mage", "primaryPosition" : "jungle", "secondaryPosition" : null},
  {champId : "25", name : "Ezreal", "primaryRole": "marksman", "secondaryRole": "mage", "primaryPosition" : "bottom", "secondaryPosition" : "middle"},
  {champId : "26", name : "Fiddlesticks", "primaryRole": "mage", "secondaryRole": "support", "primaryPosition" : "middle", "secondaryPosition" : "support"},
  {champId : "27", name : "Fiora", "primaryRole": "fighter", "secondaryRole": "assassin", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "28", name : "Fizz", "primaryRole": "assassin", "secondaryRole": "fighter", "primaryPosition" : "middle", "secondaryPosition" : "jungle"},
  {champId : "29", name : "Galio", "primaryRole": "tank", "secondaryRole": "mage", "primaryPosition" : "top", "secondaryPosition" : "middle"},
  {champId : "30", name : "Gangplank", "primaryRole": "fighter", "secondaryRole": null, "primaryPosition" : "top", "secondaryPosition" : null},
  {champId : "31", name : "Garen", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "32", name : "Gnar", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "33", name : "Gragas", "primaryRole": "fighter", "secondaryRole": "mage", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "34", name : "Graves", "primaryRole": "marksman", "secondaryRole": null, "primaryPosition" : "bottom", "secondaryPosition" : null},
  {champId : "35", name : "Hecarim", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "36", name : "Heimerdinger", "primaryRole": "mage", "secondaryRole": "support", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "37", name : "Illaoi", "primaryRole:": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "38", name : "Irelia", "primaryRole": "fighter", "secondaryRole": "assassin", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "39", name : "Janna", "primaryRole": "support", "secondaryRole": "mage", "primaryPosition" : "support", "secondaryPosition" : null},
  {champId : "40", name : "JarvanIV", "primaryRole": "tank", "secondaryRole": "fighter", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "41", name : "Jax", "primaryRole": "fighter", "secondaryRole": "assassin", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "42", name : "Jayce", "primaryRole": "marksman", "secondaryRole": "fighter", "primaryPosition" : "top", "secondaryPosition" : null},
  {champId : "43", name : "Jinx", "primaryRole": "marksman", "secondaryRole": null, "primaryPosition" : "bottom", "secondaryPosition" : null},
  {champId : "44", name : "Kalista", "primaryRole": "marksman", "secondaryRole": null, "primaryPosition" : "bottom", "secondaryPosition" : null},
  {champId : "45", name : "Karma", "primaryRole": "mage", "secondaryRole": "support", "primaryPosition" : "middle", "secondaryPosition" : "support"},
  {champId : "46", name : "Karthus", "primaryRole": "mage", "secondaryRole": null, "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "47", name : "Kassadin", "primaryRole": "assassin", "secondaryRole": "mage", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "48", name : "Katarina", "primaryRole": "assassin", "secondaryRole": "mage", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "49", name : "Kayle", "primaryRole": "fighter", "secondaryRole": "support", "primaryPosition" : "middle", "secondaryPosition" : "support"},
  {champId : "50", name : "Kennen", "primaryRole": "mage", "secondaryRole": "marksman", "primaryPosition" : "middle", "secondaryPosition" : "top"},
  {champId : "51", name : "KhaZix", "primaryRole": "assassin", "secondaryRole": "fighter", "primaryPosition" : "jungle", "secondaryPosition" : "top"},
  {champId : "52", name : "Kindred", "primaryRole" : "marksman", "secondaryRole" : null, "primaryPosition" : "jungle", "secondaryPosition" : "top"},
  {champId : "53", name : "KogMaw", "primaryRole": "marksman", "secondaryRole": "mage", "primaryPosition" : "bottom", "secondaryPosition" : "middle"},
  {champId : "54", name : "LeBlanc", "primaryRole": "assassin", "secondaryRole": "mage", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "55", name : "LeeSin", "primaryRole": "fighter", "secondaryRole": "assassin", "primaryPosition" : "jungle", "secondaryPosition" : "top"},
  {champId : "56", name : "Leona", "primaryRole": "tank", "secondaryRole": "support", "primaryPosition" : "support", "secondaryPosition" : "top"},
  {champId : "57", name : "Lissandra", "primaryRole": "mage", "secondaryRole": null, "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "58", name : "Lucian", "primaryRole": "marksman", "secondaryRole": null, "primaryPosition" : "bottom", "secondaryPosition" : null},
  {champId : "59", name : "Lulu", "primaryRole": "support", "secondaryRole": "mage", "primaryPosition" : "support", "secondaryPosition" : null},
  {champId : "60", name : "Lux", "primaryRole": "mage", "secondaryRole": "support", "primaryPosition" : "middle", "secondaryPosition" : "support"},
  {champId : "61", name : "Malphite", "primaryRole": "tank", "secondaryRole": "fighter", "primaryPosition" : "top", "secondaryPosition" : "support"},
  {champId : "62", name : "Malzahar", "primaryRole": "mage", "secondaryRole": "assassin", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "63", name : "Maokai", "primaryRole": "tank", "secondaryRole": "mage", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "64", name : "MasterYi", "primaryRole": "assassin", "secondaryRole": "fighter", "primaryPosition" : "jungle", "secondaryPosition" : "top"},
  {champId : "65", name : "MissFortune", "primaryRole": "marksman", "secondaryRole": null, "primaryPosition" : "bottom", "secondaryPosition" : null},
  {champId : "66", name : "Mordekaiser", "primaryRole": "fighter", "secondaryRole": "mage", "primaryPosition" : "jungle", "secondaryPosition" : "top"},
  {champId : "67", name : "Morgana", "primaryRole": "mage", "secondaryRole": "support", "primaryPosition" : "middle", "secondaryPosition" : "support"},
  {champId : "68", name : "Nami", "primaryRole": "support", "secondaryRole": "mage", "primaryPosition" : "support", "secondaryPosition" : null},
  {champId : "69", name : "Nasus", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : null},
  {champId : "70", name : "Nautilus", "primaryRole": "tank", "secondaryRole": "fighter", "primaryPosition" : "support", "secondaryPosition" : "jungle"},
  {champId : "71", name : "Nidalee", "primaryRole": "assassin", "secondaryRole": "fighter", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "72", name : "Nocturne", "primaryRole": "assassin", "secondaryRole": "fighter", "primaryPosition" : "jungle", "secondaryPosition" : "top"},
  {champId : "73", name : "Nunu", "primaryRole": "support", "secondaryRole": "fighter", "primaryPosition" : "support", "secondaryPosition" : "jungle"},
  {champId : "74", name : "Olaf", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "75", name : "Orianna", "primaryRole": "mage", "secondaryRole": "support", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "76", name : "Pantheon", "primaryRole": "fighter", "secondaryRole": "assassin", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "77", name : "Poppy", "primaryRole": "fighter", "secondaryRole": "assassin", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "78", name : "Quinn", "primaryRole": "marksman", "secondaryRole": "fighter", "primaryPosition" : "bottom", "secondaryPosition" : "top"},
  {champId : "79", name : "Rammus", "primaryRole": "tank", "secondaryRole": "fighter", "primaryPosition" : "jungle", "secondaryPosition" : "top"},
  {champId : "80", name : "Reksai", "primaryRole": "fighter", "secondaryRole": null, "primaryPosition" : "jungle", "secondaryPosition" : "top"},
  {champId : "81", name : "Renekton", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "82", name : "Rengar", "primaryRole": "assassin", "secondaryRole": "fighter", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "83", name : "Riven", "primaryRole": "fighter", "secondaryRole": "assassin", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "84", name : "Rumble", "primaryRole": "fighter", "secondaryRole": "mage", "primaryPosition" : "top", "secondaryPosition" : "middle"},
  {champId : "85", name : "Ryze", "primaryRole": "mage", "secondaryRole": "fighter", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "86", name : "Sejuani", "primaryRole": "tank", "secondaryRole": "fighter", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "87", name : "Shaco", "primaryRole": "assassin", "secondaryRole": null, "primaryPosition" : "jungle", "secondaryPosition" : "top"},
  {champId : "88", name : "Shen", "primaryRole": "tank", "secondaryRole": "fighter", "primaryPosition" : "top", "secondaryPosition" : "support"},
  {champId : "89", name : "Shyvana", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "90", name : "Singed", "primaryRole": "tank", "secondaryRole": "fighter", "primaryPosition" : "top", "secondaryPosition" : null},
  {champId : "91", name : "Sion", "primaryRole": "tank", "secondaryRole": "fighter", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "92", name : "Sivir", "primaryRole": "marksman", "secondaryRole": null, "primaryPosition" : "bottom", "secondaryPosition" : null},
  {champId : "93", name : "Skarner", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "jungle", "secondaryPosition" : "top"},
  {champId : "94", name : "Sona", "primaryRole": "support", "secondaryRole": "mage", "primaryPosition" : "support", "secondaryPosition" : null},
  {champId : "95", name : "Soraka", "primaryRole": "support", "secondaryRole": "mage", "primaryPosition" : "support", "secondaryPosition" : null},
  {champId : "96", name : "Swain", "primaryRole": "mage", "secondaryRole": "fighter", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "97", name : "Syndra", "primaryRole": "mage", "secondaryRole": "support", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "98", name : "TahmKench", "primaryRole": "support", "secondaryRole": "tank", "primaryPosition" : "support", "secondaryPosition" : "top"},
  {champId : "99", name : "Talon", "primaryRole": "assassin", "secondaryRole": "fighter", "primaryPosition" : "jungle", "secondaryPosition" : "top"},
  {champId : "100", name : "Taric", "primaryRole": "support", "secondaryRole": "fighter", "primaryPosition" : "support", "secondaryPosition" : "top"},
  {champId : "101", name : "Teemo", "primaryRole": "marksman", "secondaryRole": "assassin", "primaryPosition" : "top", "secondaryPosition" : "support"},
  {champId : "102", name : "Thresh", "primaryRole": "support", "secondaryRole": "fighter", "primaryPosition" : "support", "secondaryPosition" : null},
  {champId : "103", name : "Tristana", "primaryRole": "marksman", "secondaryRole": "assassin", "primaryPosition" : "bottom", "secondaryPosition" : null},
  {champId : "104", name : "Trundle", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "105", name : "Tryndamere", "primaryRole": "fighter", "secondaryRole": "assassin", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "106", name : "TwistedFate", "primaryRole": "mage", "secondaryRole": null, "primaryPosition" : "middle", "secondaryPosition" : "jungle"},
  {champId : "107", name : "Twitch", "primaryRole": "marksman", "secondaryRole": "assassin", "primaryPosition" : "bottom", "secondaryPosition" : null},
  {champId : "108", name : "Udyr", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "109", name : "Urgot", "primaryRole": "marksman", "secondaryRole": "fighter", "primaryPosition" : "top", "secondaryPosition" : null},
  {champId : "110", name : "Varus", "primaryRole": "marksman", "secondaryRole": "mage", "primaryPosition" : "bottom", "secondaryPosition" : null},
  {champId : "111", name : "Vayne", "primaryRole": "marksman", "secondaryRole": "assassin", "primaryPosition" : "bottom", "secondaryPosition" : null},
  {champId : "112", name : "Veigar", "primaryRole": "mage", "secondaryRole": null, "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "113", name : "Velkoz", "primaryRole": "mage", "secondaryRole": null, "primaryPosition" : "middle", "secondaryPosition" : "support"},
  {champId : "114", name : "Vi", "primaryRole": "fighter", "secondaryRole": "assassin", "primaryPosition" : "jungle", "secondaryPosition" : "top"},
  {champId : "115", name : "Viktor", "primaryRole": "mage", "secondaryRole": null, "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "116", name : "Vladimir", "primaryRole": "mage", "secondaryRole": "tank", "primaryPosition" : "middle", "secondaryPosition" : "top"},
  {champId : "117", name : "Volibear", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "118", name : "Warwick", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "jungle", "secondaryPosition" : "top"},
  {champId : "119", name : "Wukong", "primaryRole": "fighter", "secondaryRole": "tank", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "120", name : "Xerath", "primaryRole": "mage", "secondaryRole": "assassin", "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "121", name : "XinZhao", "primaryRole": "fighter", "secondaryRole": "assassin", "primaryPosition" : "top", "secondaryPosition" : "jungle"},
  {champId : "122", name : "Yasuo", "primaryRole": "fighter", "secondaryRole": "assassin", "primaryPosition" : "top", "secondaryPosition" : "middle"},
  {champId : "123", name : "Yorick", "primaryRole": "fighter", "secondaryRole": "mage", "primaryPosition" : "top", "secondaryPosition" : null},
  {champId : "124", name : "Zac", "primaryRole": "tank", "secondaryRole": "fighter", "primaryPosition" : "jungle", "secondaryPosition" : "top"},
  {champId : "125", name : "Zed", "primaryRole": "assassin", "secondaryRole": "fighter", "primaryPosition" : "top", "secondaryPosition" : "middle"},
  {champId : "126", name : "Ziggs", "primaryRole": "mage", "secondaryRole": null, "primaryPosition" : "middle", "secondaryPosition" : null},
  {champId : "127", name : "Zilean", "primaryRole": "support", "secondaryRole": "mage", "primaryPosition" : "support", "secondaryPosition" : "middle"},
  {champId : "128", name : "Zyra", "primaryRole": "support", "secondaryRole": "mage", "primaryPosition" : "support", "secondaryPosition" : "middle"}
];
var friends = [
  { champId : "1", friendId: "9"},
  { champId : "1", friendId: "32"}, 
  { champId : "1", friendId: "81"},
  { champId : "1", friendId: "105"},
  { champId : "1", friendId: "122"},
  { champId : "1", friendId: "127"},
  { champId : "2", friendId: "3"},
  { champId : "2", friendId: "25"},
  { champId : "2", friendId: "38"}, 
  { champId : "2", friendId: "41"},
  { champId : "2", friendId: "83"}, 
  { champId : "2", friendId: "88"},
  { champId : "3", friendId: "1"},
  { champId : "3", friendId: "2"},
  { champId : "3", friendId: "19"},
  { champId : "3", friendId: "48"},
  { champId : "3", friendId: "54"}, 
  { champId : "3", friendId: "88"},
  { champId : "4", friendId: "11"}, 
  { champId : "4", friendId: "14"},
  { champId : "4", friendId: "25"},
  { champId : "4", friendId: "103"},
  { champId : "4", friendId: "111"},
  { champId : "4", friendId: "Yasuo"},
  { champId : "Amumu", friendId: "Annie"}, 
  { champId : "Amumu", friendId: "Fiddlesticks"},
  { champId : "Amumu", friendId: "Fizz"}, 
  { champId : "Amumu", friendId: "Katarina"},
  { champId : "Amumu", friendId: "Kennen"},
  { champId : "Amumu", friendId: "Morgana"},
  { champId : "Anivia", friendId: "Ashe"},
  { champId : "Anivia", friendId: "DrMundo"},
  { champId : "Anivia", friendId: "JarvanIV"}, 
  { champId : "Anivia", friendId: "Maokai"},
  { champId : "Anivia", friendId: "Trundle"}, 
  { champId : "Anivia", friendId: "Vayne"},
  { champId : "Annie", friendId: "Amumu"},
  { champId : "Annie", friendId: "Blitzcrank"},
  { champId : "Annie", friendId: "Caitlyn"},
  { champId : "Annie", friendId: "Ezreal"},
  { champId : "Annie", friendId: "Jinx"}, 
  { champId : "Annie", friendId: "Lucian"},
  { champId : "Ashe", friendId: "Blitzcrank"}, 
  { champId : "Ashe", friendId: "Janna"},
  { champId : "Ashe", friendId: "Leona"},
  { champId : "Ashe", friendId: "Sona"},
  { champId : "Ashe", friendId: "Thresh"},
  { champId : "Ashe", friendId: "Zyra"},
  { champId : "Azir", friendId: "Aatrox"}, 
  { champId : "Azir", friendId: "Blitzcrank"},
  { champId : "Azir", friendId: "Sejuani"}, 
  { champId : "Azir", friendId: "Sivir"},
  { champId : "Azir", friendId: "Thresh"},
  { champId : "Azir", friendId: "Yasuo"},
  { champId : "Bard", friendId: "Amumu"},
  { champId : "Bard", friendId: "Caitlyn"},
  { champId : "Bard", friendId: "Draven"}, 
  { champId : "Bard", friendId: "Ezreal"},
  { champId : "Bard", friendId: "Jinx"}, 
  { champId : "Bard", friendId: "Udyr"},
  { champId : "Blitzcrank", friendId: "Caitlyn"},
  { champId : "Blitzcrank", friendId: "Draven"},
  { champId : "Blitzcrank", friendId: "Ezreal"},
  { champId : "Blitzcrank", friendId: "Graves"},
  { champId : "Blitzcrank", friendId: "Jinx"}, 
  { champId : "Blitzcrank", friendId: "Vayne"},
  { champId : "Brand", friendId: "Amumu"}, 
  { champId : "Brand", friendId: "JarvanIV"},
  { champId : "Brand", friendId: "Maokai"},
  { champId : "Brand", friendId: "Malphite"},
  { champId : "Brand", friendId: "Sona"},
  { champId : "Brand", friendId: "Vladimir"},
  { champId : "Braum", friendId: "Ashe"}, 
  { champId : "Braum", friendId: "Caitlyn"},
  { champId : "Braum", friendId: "Ezreal"}, 
  { champId : "Braum", friendId: "Lucian"},
  { champId : "Braum", friendId: "Twitch"},
  { champId : "Braum", friendId: "Vayne"},
  { champId : "Caitlyn", friendId: "Blitzcrank"},
  { champId : "Caitlyn", friendId: "Leona"},
  { champId : "Caitlyn", friendId: "Nidalee"}, 
  { champId : "Caitlyn", friendId: "Nunu"},
  { champId : "Caitlyn", friendId: "Thresh"}, 
  { champId : "Caitlyn", friendId: "Vi"},
  { champId : "Cassiopeia", friendId: "Amumu"},
  { champId : "Cassiopeia", friendId: "Malphite"},
  { champId : "Cassiopeia", friendId: "Singed"},
  { champId : "Cassiopeia", friendId: "Teemo"},
  { champId : "Cassiopeia", friendId: "Twitch"}, 
  { champId : "Cassiopeia", friendId: "Yorick"},
  { champId : "ChoGath", friendId: "Aatrox"}, 
  { champId : "ChoGath", friendId: "Darius"},
  { champId : "ChoGath", friendId: "Kassadin"},
  { champId : "ChoGath", friendId: "Lulu"},
  { champId : "ChoGath", friendId: "Teemo"},
  { champId : "ChoGath", friendId: "Yasuo"},
  { champId : "Corki", friendId: "Blitzcrank"}, 
  { champId : "Corki", friendId: "Leona"},
  { champId : "Corki", friendId: "Sona"}, 
  { champId : "Corki", friendId: "Soraka"},
  { champId : "Corki", friendId: "Taric"},
  { champId : "Corki", friendId: "Thresh"},
  { champId : "Darius", friendId: "Blitzcrank"},
  { champId : "Darius", friendId: "Draven"},
  { champId : "Darius", friendId: "Fiora"}, 
  { champId : "Darius", friendId: "Garen"},
  { champId : "Darius", friendId: "Olaf"}, 
  { champId : "Darius", friendId: "Pantheon"},
  { champId : "Diana", friendId: "Akali"},
  { champId : "Diana", friendId: "Kassadin"},
  { champId : "Diana", friendId: "Katarina"},
  { champId : "Diana", friendId: "Leona"},
  { champId : "Diana", friendId: "Orianna"}, 
  { champId : "Diana", friendId: "Yasuo"},
  { champId : "DrMundo", friendId: "Anivia"}, 
  { champId : "DrMundo", friendId: "Jax"},
  { champId : "DrMundo", friendId: "Nidalee"},
  { champId : "DrMundo", friendId: "Olaf"},
  { champId : "DrMundo", friendId: "Singed"},
  { champId : "DrMundo", friendId: "Teemo"},
  { champId : "Draven", friendId: "Blitzcrank"}, 
  { champId : "Draven", friendId: "Darius"},
  { champId : "Draven", friendId: "Janna"}, 
  { champId : "Draven", friendId: "Leona"},
  { champId : "Draven", friendId: "Taric"},
  { champId : "Draven", friendId: "Thresh"},
  { champId : "Ekko", friendId: "Amumu"},
  { champId : "Ekko", friendId: "Draven"},
  { champId : "Ekko", friendId: "Gnar"}, 
  { champId : "Ekko", friendId: "LeeSin"},
  { champId : "Ekko", friendId: "Sejuani"}, 
  { champId : "Ekko", friendId: "Vi"},
  { champId : "Elise", friendId: "Ahri"},
  { champId : "Elise", friendId: "Blitzcrank"},
  { champId : "Elise", friendId: "Darius"},
  { champId : "Elise", friendId: "Karma"},
  { champId : "Elise", friendId: "Leona"}, 
  { champId : "Elise", friendId: "Rengar"},
  { champId : "Evelynn", friendId: "ChoGath"}, 
  { champId : "Evelynn", friendId: "Orianna"},
  { champId : "Evelynn", friendId: "Shaco"},
  { champId : "Evelynn", friendId: "Shen"},
  { champId : "Evelynn", friendId: "Twitch"},
  { champId : "Evelynn", friendId: "Xerath"},
  { champId : "Ezreal", friendId: "Blitzcrank"}, 
  { champId : "Ezreal", friendId: "Leona"},
  { champId : "Ezreal", friendId: "Lux"}, 
  { champId : "Ezreal", friendId: "Sona"},
  { champId : "Ezreal", friendId: "Soraka"},
  { champId : "Ezreal", friendId: "Taric"},
  { champId : "Fiddlesticks", friendId: "Amumu"},
  { champId : "Fiddlesticks", friendId: "Galio"},  
  { champId : "Fiddlesticks", friendId: "JarvanIV"},
  { champId : "Fiddlesticks", friendId: "Kennen"}, 
  { champId : "Fiddlesticks", friendId: "Orianna"},
  { champId : "Fiddlesticks", friendId: "Wukong"}, 
  { champId : "Fiora", friendId: "Ahri"},
  { champId : "Fiora", friendId: "Amumu"},
  { champId : "Fiora", friendId: "Darius"},
  { champId : "Fiora", friendId: "JarvanIV"}, 
  { champId : "Fiora", friendId: "Morgana"},
  { champId : "Fiora", friendId: "Volibear"}, 
  { champId : "Fizz", friendId: "Aatrox"},
  { champId : "Fizz", friendId: "Amumu"},
  { champId : "Fizz", friendId: "JarvanIV"},
  { champId : "Fizz", friendId: "Malphite"},
  { champId : "Fizz", friendId: "Nami"},
  { champId : "Fizz", friendId: "Talon"}, 
  { champId : "Galio", friendId: "Amumu"},
  { champId : "Galio", friendId: "Fiddlesticks"}, 
  { champId : "Galio", friendId: "Katarina"},
  { champId : "Galio", friendId: "Kennen"},
  { champId : "Galio", friendId: "Nunu"},
  { champId : "Galio", friendId: "Wukong"},
  { champId : "Gangplank", friendId: "Aatrox"},
  { champId : "Gangplank", friendId: "Amumu"}, 
  { champId : "Gangplank", friendId: "Hecarim"},
  { champId : "Gangplank", friendId: "Nunu"}, 
  { champId : "Gangplank", friendId: "Quinn"},
  { champId : "Gangplank", friendId: "TwistedFate"},
  { champId : "Garen", friendId: "Aatrox"},
  { champId : "Garen", friendId: "Alistar"},
  { champId : "Garen", friendId: "Darius"},
  { champId : "Garen", friendId: "JarvanIV"}, 
  { champId : "Garen", friendId: "Lux"},
  { champId : "Garen", friendId: "XinZhao"}, 
  { champId : "Gnar", friendId: "Aatrox"},
  { champId : "Gnar", friendId: "Amumu"},
  { champId : "Gnar", friendId: "Braum"},
  { champId : "Gnar", friendId: "JarvanIV"},
  { champId : "Gnar", friendId: "Lulu"},
  { champId : "Gnar", friendId: "Orianna"}, 
  { champId : "Gragas", friendId: "Aatrox"},
  { champId : "Gragas", friendId: "Ashe"}, 
  { champId : "Gragas", friendId: "Jayce"},
  { champId : "Gragas", friendId: "KhaZix"},
  { champId : "Gragas", friendId: "Malphite"},
  { champId : "Gragas", friendId: "Sejuani"},
  { champId : "Graves", friendId: "Blitzcrank"},
  { champId : "Graves", friendId: "Leona"}, 
  { champId : "Graves", friendId: "Nami"},
  { champId : "Graves", friendId: "Soraka"}, 
  { champId : "Graves", friendId: "Taric"},
  { champId : "Graves", friendId: "Thresh"},
  { champId : "Hecarim", friendId: "Gangplank"},
  { champId : "Hecarim", friendId: "Janna"},
  { champId : "Hecarim", friendId: "Jayce"},
  { champId : "Hecarim", friendId: "Lulu"}, 
  { champId : "Hecarim", friendId: "Orianna"},
  { champId : "Hecarim", friendId: "Zilean"}, 
  { champId : "Heimerdinger", friendId: "Amumu"},
  { champId : "Heimerdinger", friendId: "Blitzcrank"},
  { champId : "Heimerdinger", friendId: "Skarner"},
  { champId : "Heimerdinger", friendId: "Teemo"},
  { champId : "Heimerdinger", friendId: "Thresh"},
  { champId : "Heimerdinger", friendId: "Vi"}, 
  { champId : "Illaoi", friendId: "Blitzcrank"},
  { champId : "Illaoi", friendId: "Kalista"}, 
  { champId : "Illaoi", friendId: "Lulu"},
  { champId : "Illaoi", friendId: "Orianna"},
  { champId : "Illaoi", friendId: "Thresh"},
  { champId : "Illaoi", friendId: "Zilean"},
  { champId : "Irelia", friendId: "Ahri"},
  { champId : "Irelia", friendId: "Akali"}, 
  { champId : "Irelia", friendId: "LeeSin"},
  { champId : "Irelia", friendId: "Malphite"}, 
  { champId : "Irelia", friendId: "Nunu"},
  { champId : "Irelia", friendId: "Riven"},
  { champId : "Janna", friendId: "Ashe"},
  { champId : "Janna", friendId: "Caitlyn"},
  { champId : "Janna", friendId: "Draven"},
  { champId : "Janna", friendId: "Ezreal"}, 
  { champId : "Janna", friendId: "Vayne"},
  { champId : "Janna", friendId: "Yasuo"}, 
  { champId : "JarvanIV", friendId: "Anivia"},
  { champId : "JarvanIV", friendId: "Katarina"},
  { champId : "JarvanIV", friendId: "MissFortune"},
  { champId : "JarvanIV", friendId: "Orianna"},
  { champId : "JarvanIV", friendId: "Wukong"},
  { champId : "JarvanIV", friendId: "XinZhao"}, 
  { champId : "Jax", friendId: "Ahri"},
  { champId : "Jax", friendId: "Orianna"}, 
  { champId : "Jax", friendId: "Pantheon"},
  { champId : "Jax", friendId: "Ryze"},
  { champId : "Jax", friendId: "Teemo"},
  { champId : "Jax", friendId: "Zilean"},
  { champId : "Jayce", friendId: "Alistar"},
  { champId : "Jayce", friendId: "Blitzcrank"}, 
  { champId : "Jayce", friendId: "Leona"},
  { champId : "Jayce", friendId: "Nidalee"}, 
  { champId : "Jayce", friendId: "Skarner"},
  { champId : "Jayce", friendId: "Soraka"},
  { champId : "Jinx", friendId: "Annie"},
  { champId : "Jinx", friendId: "Blitzcrank"},
  { champId : "Jinx", friendId: "Leona"},
  { champId : "Jinx", friendId: "Morgana"}, 
  { champId : "Jinx", friendId: "Nami"},
  { champId : "Jinx", friendId: "Thresh"},
  { champId : "Kalista", friendId: "Amumu"},   
  { champId : "Kalista", friendId: "Illaoi"},
  { champId : "Kalista", friendId: "Janna"},
  { champId : "Kalista", friendId: "Leona"},
  { champId : "Kalista", friendId: "Malphite"},
  { champId : "Kalista", friendId: "Thresh"},
  { champId : "Karma", friendId: "Caitlyn"},
  { champId : "Karma", friendId: "Ezreal"}, 
  { champId : "Karma", friendId: "Jinx"},
  { champId : "Karma", friendId: "Lucian"},
  { champId : "Karma", friendId: "Sivir"},
  { champId : "Karma", friendId: "Vayne"},
  { champId : "Karthus", friendId: "Amumu"},
  { champId : "Karthus", friendId: "Kayle"}, 
  { champId : "Karthus", friendId: "Nocturne"},
  { champId : "Karthus", friendId: "Soraka"}, 
  { champId : "Karthus", friendId: "Vladimir"},
  { champId : "Karthus", friendId: "Yorick"},
  { champId : "Kassadin", friendId: "Aatrox"},
  { champId : "Kassadin", friendId: "Ahri"},
  { champId : "Kassadin", friendId: "Amumu"},
  { champId : "Kassadin", friendId: "ChoGath"}, 
  { champId : "Kassadin", friendId: "Diana"},
  { champId : "Kassadin", friendId: "LeeSin"}, 
  { champId : "Katarina", friendId: "Akali"},
  { champId : "Katarina", friendId: "Amumu"},
  { champId : "Katarina", friendId: "Galio"},
  { champId : "Katarina", friendId: "JarvanIV"},
  { champId : "Katarina", friendId: "Malphite"},
  { champId : "Katarina", friendId: "Morgana"}, 
  { champId : "Kayle", friendId: "Ezreal"},
  { champId : "Kayle", friendId: "Karthus"}, 
  { champId : "Kayle", friendId: "Katarina"},
  { champId : "Kayle", friendId: "Nasus"},
  { champId : "Kayle", friendId: "Tryndamere"},
  { champId : "Kayle", friendId: "Zed"},
  { champId : "Kennen", friendId: "Amumu" },
  { champId : "Kennen", friendId: "Fiddlesticks" },
  { champId : "Kennen", friendId: "Galio" },
  { champId : "Kennen", friendId: "Nunu" },
  { champId : "Kennen", friendId: "Vladimir" },
  { champId : "Kennen", friendId: "Wukong" },
  { champId : "KhaZix", friendId: "Aatrox" },
  { champId : "KhaZix", friendId: "Blitzcrank" },
  { champId : "KhaZix", friendId: "Morgana" },
  { champId : "KhaZix", friendId: "Nasus" },
  { champId : "KhaZix", friendId: "Rengar" },
  { champId : "KhaZix", friendId: "XinZhao" },
  { champId : "Kindred", friendId: "Alistar" },
  { champId : "Kindred", friendId: "Amumu" },  
  { champId : "Kindred", friendId: "Ashe" },
  { champId : "Kindred", friendId: "Blitzcrank" }, 
  { champId : "Kindred", friendId: "Kindred" },
  { champId : "Kindred", friendId: "Thresh" },
  { champId : "KogMaw", friendId: "Janna" },
  { champId : "KogMaw", friendId: "Lulu" },
  { champId : "KogMaw", friendId: "Nami" },
  { champId : "KogMaw", friendId: "Nunu" },
  { champId : "KogMaw", friendId: "Sona" },
  { champId : "KogMaw", friendId: "Soraka" },
  { champId : "LeBlanc", friendId: "Aatrox" },
  { champId : "LeBlanc", friendId: "Akali" },
  { champId : "LeBlanc", friendId: "Alistar" },
  { champId : "LeBlanc", friendId: "Amumu" },
  { champId : "LeBlanc", friendId: "Udyr" },
  { champId : "LeBlanc", friendId: "Veigar" },
  { champId : "LeeSin", friendId: "Aatrox" },
  { champId : "LeeSin", friendId: "Kassadin" },
  { champId : "LeeSin", friendId: "Ryze" },
  { champId : "LeeSin", friendId: "Teemo" },
  { champId : "LeeSin", friendId: "Warwick" },
  { champId : "LeeSin", friendId: "Yasuo" },
  { champId : "Leona", friendId: "Corki" },
  { champId : "Leona", friendId: "Ezreal" },
  { champId : "Leona", friendId: "Jinx" },
  { champId : "Leona", friendId: "Tristana" },
  { champId : "Leona", friendId: "Varus" },
  { champId : "Leona", friendId: "Vayne" },
  { champId : "Lissandra", friendId: "Amumu" },
  { champId : "Lissandra", friendId: "Ashe" },
  { champId : "Lissandra", friendId: "JarvanIV" },
  { champId : "Lissandra", friendId: "Nunu" },
  { champId : "Lissandra", friendId: "Sejuani" },
  { champId : "Lissandra", friendId: "Trundle" },
  { champId : "Lucian", friendId: "Blitzcrank" },
  { champId : "Lucian", friendId: "Braum" },
  { champId : "Lucian", friendId: "Leona" },
  { champId : "Lucian", friendId: "Nami" },
  { champId : "Lucian", friendId: "Soraka" },
  { champId : "Lucian", friendId: "Thresh" },
  { champId : "Lulu", friendId: "Caitlyn" },
  { champId : "Lulu", friendId: "ChoGath" },
  { champId : "Lulu", friendId: "Ezreal" },
  { champId : "Lulu", friendId: "KogMaw" },
  { champId : "Lulu", friendId: "Tristana" },
  { champId : "Lulu", friendId: "Vayne" },
  { champId : "Lux", friendId: "Ashe" },
  { champId : "Lux", friendId: "Caitlyn" },
  { champId : "Lux", friendId: "Ezreal" },
  { champId : "Lux", friendId: "Garen" },
  { champId : "Lux", friendId: "Jinx" },
  { champId : "Lux", friendId: "Varus" },
  { champId : "Malphite", friendId: "Fizz" },
  { champId : "Malphite", friendId: "Gragas" },
  { champId : "Malphite", friendId: "Katarina" },
  { champId : "Malphite", friendId: "Mordekaiser" },
  { champId : "Malphite", friendId: "Orianna" },
  { champId : "Malphite", friendId: "Yasuo" },
  { champId : "Malzahar", friendId: "Amumu" },
  { champId : "Malzahar", friendId: "JarvanIV" },
  { champId : "Malzahar", friendId: "Maokai" },
  { champId : "Malzahar", friendId: "Skarner" },
  { champId : "Malzahar", friendId: "Viktor" },
  { champId : "Malzahar", friendId: "Warwick" },
  { champId : "Maokai", friendId: "Anivia" },
  { champId : "Maokai", friendId: "Orianna" },
  { champId : "Maokai", friendId: "Rumble" },
  { champId : "Maokai", friendId: "Ryze" },
  { champId : "Maokai", friendId: "Swain" },
  { champId : "Maokai", friendId: "Vladimir" },
  { champId : "MasterYi", friendId: "Aatrox" },
  { champId : "MasterYi", friendId: "Amumu" },
  { champId : "MasterYi", friendId: "Ashe" },
  { champId : "MasterYi", friendId: "Jax" },
  { champId : "MasterYi", friendId: "Lux" },
  { champId : "MasterYi", friendId: "Morgana" },
  { champId : "MissFortune", friendId: "Blitzcrank" },
  { champId : "MissFortune", friendId: "Leona" },
  { champId : "MissFortune", friendId: "Nami" },
  { champId : "MissFortune", friendId: "Sona" },
  { champId : "MissFortune", friendId: "Taric" },
  { champId : "MissFortune", friendId: "Thresh" },
  { champId : "Mordekaiser", friendId: "Amumu" },
  { champId : "Mordekaiser", friendId: "Kayle" },
  { champId : "Mordekaiser", friendId: "Malphite" },
  { champId : "Mordekaiser", friendId: "Warwick" },
  { champId : "Mordekaiser", friendId: "Wukong" },
  { champId : "Mordekaiser", friendId: "Yorick" },
  { champId : "Morgana", friendId: "Amumu" },
  { champId : "Morgana", friendId: "Caitlyn" },
  { champId : "Morgana", friendId: "Draven" },
  { champId : "Morgana", friendId: "Jinx" },
  { champId : "Morgana", friendId: "Katarina" },
  { champId : "Morgana", friendId: "Varus" },
  { champId : "Nami", friendId: "Caitlyn" },
  { champId : "Nami", friendId: "Draven" },
  { champId : "Nami", friendId: "Graves" },
  { champId : "Nami", friendId: "Jinx" },
  { champId : "Nami", friendId: "Varus" },
  { champId : "Nami", friendId: "Vayne" },
  { champId : "Nasus", friendId: "Kayle" },
  { champId : "Nasus", friendId: "KhaZix" },
  { champId : "Nasus", friendId: "Lulu" },
  { champId : "Nasus", friendId: "Renekton" },
  { champId : "Nasus", friendId: "Ryze" },
  { champId : "Nasus", friendId: "Zed" },
  { champId : "Nautilus", friendId: "Draven" },
  { champId : "Nautilus", friendId: "Ezreal" },
  { champId : "Nautilus", friendId: "Shyvana" },
  { champId : "Nautilus", friendId: "Varus" },
  { champId : "Nautilus", friendId: "Vayne" },
  { champId : "Nautilus", friendId: "Yasuo" },
  { champId : "Nidalee", friendId: "Ashe" },
  { champId : "Nidalee", friendId: "Caitlyn" },
  { champId : "Nidalee", friendId: "Ezreal" },
  { champId : "Nidalee", friendId: "Jayce" },
  { champId : "Nidalee", friendId: "Jinx" },
  { champId : "Nidalee", friendId: "Varus" },
  { champId : "Nocturne", friendId: "Lucian" },
  { champId : "Nocturne", friendId: "Malzahar" },
  { champId : "Nocturne", friendId: "Orianna" },
  { champId : "Nocturne", friendId: "Rengar" },
  { champId : "Nocturne", friendId: "Shen" },
  { champId : "Nocturne", friendId: "TwistedFate" },
  { champId : "Nunu", friendId: "Ashe" },
  { champId : "Nunu", friendId: "Caitlyn" },
  { champId : "Nunu", friendId: "Draven" },
  { champId : "Nunu", friendId: "KogMaw" },
  { champId : "Nunu", friendId: "MissFortune" },
  { champId : "Nunu", friendId: "Vayne" },
  { champId : "Olaf", friendId: "Aatrox" },
  { champId : "Olaf", friendId: "Amumu" },
  { champId : "Olaf", friendId: "Blitzcrank" },
  { champId : "Olaf", friendId: "Darius" },
  { champId : "Olaf", friendId: "DrMundo" },
  { champId : "Olaf", friendId: "Tryndamere" },
  { champId : "Orianna", friendId: "Amumu" },
  { champId : "Orianna", friendId: "JarvanIV" },
  { champId : "Orianna", friendId: "Malphite" },
  { champId : "Orianna", friendId: "Wukong" },
  { champId : "Orianna", friendId: "Yasuo" },
  { champId : "Orianna", friendId: "Zac" },
  { champId : "Pantheon", friendId: "Blitzcrank" },
  { champId : "Pantheon", friendId: "Darius" },
  { champId : "Pantheon", friendId: "Jax" },
  { champId : "Pantheon", friendId: "Sion" },
  { champId : "Pantheon", friendId: "Taric" },
  { champId : "Pantheon", friendId: "XinZhao" },
  { champId : "Poppy", friendId: "Aatrox" },
  { champId : "Poppy", friendId: "Alistar" },
  { champId : "Poppy", friendId: "ChoGath" },
  { champId : "Poppy", friendId: "Shen" },
  { champId : "Poppy", friendId: "Sion" },
  { champId : "Poppy", friendId: "Vayne" },
  { champId : "Quinn", friendId: "Blitzcrank" },
  { champId : "Quinn", friendId: "Janna" },
  { champId : "Quinn", friendId: "Leona" },
  { champId : "Quinn", friendId: "Nami" },
  { champId : "Quinn", friendId: "Taric" },
  { champId : "Quinn", friendId: "Thresh" },
  { champId : "Rammus", friendId: "Ahri" },
  { champId : "Rammus", friendId: "Ashe" },
  { champId : "Rammus", friendId: "Fizz" },
  { champId : "Rammus", friendId: "Shen" },
  { champId : "Rammus", friendId: "Teemo" },
  { champId : "Rammus", friendId: "TwistedFate" },
  { champId : "Reksai", friendId: "Kassadin" },
  { champId : "Reksai", friendId: "LeeSin" },
  { champId : "Reksai", friendId: "Lux" },
  { champId : "Reksai", friendId: "Malphite" },
  { champId : "Reksai", friendId: "Riven" },
  { champId : "Reksai", friendId: "Yasuo" },
  { champId : "Renekton", friendId: "Aatrox" },
  { champId : "Renekton", friendId: "Ahri" },
  { champId : "Renekton", friendId: "Amumu" },
  { champId : "Renekton", friendId: "Lulu" },
  { champId : "Renekton", friendId: "Nasus" },
  { champId : "Renekton", friendId: "Pantheon" },
  { champId : "Rengar", friendId: "Elise" },
  { champId : "Rengar", friendId: "KhaZix" },
  { champId : "Rengar", friendId: "Nocturne" },
  { champId : "Rengar", friendId: "Orianna" },
  { champId : "Rengar", friendId: "Shen" },
  { champId : "Rengar", friendId: "Zilean" },
  { champId : "Riven", friendId: "Ahri" },
  { champId : "Riven", friendId: "Amumu" },
  { champId : "Riven", friendId: "Irelia" },
  { champId : "Riven", friendId: "LeeSin" },
  { champId : "Riven", friendId: "Orianna" },
  { champId : "Riven", friendId: "Yasuo" },
  { champId : "Rumble", friendId: "Amumu" },
  { champId : "Rumble", friendId: "Galio" },
  { champId : "Rumble", friendId: "JarvanIV" },
  { champId : "Rumble", friendId: "Maokai" },
  { champId : "Rumble", friendId: "Sejuani" },
  { champId : "Rumble", friendId: "Sona" },
  { champId : "Ryze", friendId: "Amumu" },
  { champId : "Ryze", friendId: "Jax" },
  { champId : "Ryze", friendId: "LeeSin" },
  { champId : "Ryze", friendId: "Maokai" },
  { champId : "Ryze", friendId: "Talon" },
  { champId : "Ryze", friendId: "Udyr" },
  { champId : "Sejuani", friendId: "Katarina" },
  { champId : "Sejuani", friendId: "Lissandra" },
  { champId : "Sejuani", friendId: "Rumble" },
  { champId : "Sejuani", friendId: "Talon" },
  { champId : "Sejuani", friendId: "Veigar" },
  { champId : "Sejuani", friendId: "Ziggs" },
  { champId : "Shaco", friendId: "Blitzcrank" },
  { champId : "Shaco", friendId: "Evelynn" },
  { champId : "Shaco", friendId: "Heimerdinger" },
  { champId : "Shaco", friendId: "Shen" },
  { champId : "Shaco", friendId: "Singed" },
  { champId : "Shaco", friendId: "Teemo" },
  { champId : "Shen", friendId: "Ahri" },
  { champId : "Shen", friendId: "Akali" },
  { champId : "Shen", friendId: "Pantheon" },
  { champId : "Shen", friendId: "Rengar" },
  { champId : "Shen", friendId: "TwistedFate" },
  { champId : "Shen", friendId: "Zed" },
  { champId : "Shyvana", friendId: "Morgana" },
  { champId : "Shyvana", friendId: "Nautilus" },
  { champId : "Shyvana", friendId: "Orianna" },
  { champId : "Shyvana", friendId: "Riven" },
  { champId : "Shyvana", friendId: "Shen" },
  { champId : "Shyvana", friendId: "Yasuo" },
  { champId : "Singed", friendId: "Cassiopeia" },
  { champId : "Singed", friendId: "Janna" },
  { champId : "Singed", friendId: "Sion" },
  { champId : "Singed", friendId: "Teemo" },
  { champId : "Singed", friendId: "Volibear" },
  { champId : "Singed", friendId: "Zilean" },
  { champId : "Sion", friendId: "Darius" },
  { champId : "Sion", friendId: "Pantheon" },
  { champId : "Sion", friendId: "Poppy" },
  { champId : "Sion", friendId: "Singed" },
  { champId : "Sion", friendId: "Talon" },
  { champId : "Sion", friendId: "Taric" },
  { champId : "Sivir", friendId: "Leona" },
  { champId : "Sivir", friendId: "Morgana" },
  { champId : "Sivir", friendId: "Sona" },
  { champId : "Sivir", friendId: "Soraka" },
  { champId : "Sivir", friendId: "Taric" },
  { champId : "Sivir", friendId: "Thresh" },
  { champId : "Skarner", friendId: "Heimerdinger" },
  { champId : "Skarner", friendId: "Jayce" },
  { champId : "Skarner", friendId: "Malzahar" },
  { champId : "Skarner", friendId: "Orianna" },
  { champId : "Skarner", friendId: "Thresh" },
  { champId : "Skarner", friendId: "Veigar" },
  { champId : "Sona", friendId: "Ashe" },
  { champId : "Sona", friendId: "Caitlyn" },
  { champId : "Sona", friendId: "Ezreal" },
  { champId : "Sona", friendId: "Graves" },
  { champId : "Sona", friendId: "MissFortune" },
  { champId : "Sona", friendId: "Varus" },
  { champId : "Soraka", friendId: "Caitlyn" },
  { champId : "Soraka", friendId: "Ezreal" },
  { champId : "Soraka", friendId: "Graves" },
  { champId : "Soraka", friendId: "Sivir" },
  { champId : "Soraka", friendId: "Urgot" },
  { champId : "Soraka", friendId: "Varus" },
  { champId : "Swain", friendId: "Aatrox" },
  { champId : "Swain", friendId: "Alistar" },
  { champId : "Swain", friendId: "Diana" },
  { champId : "Swain", friendId: "JarvanIV" },
  { champId : "Swain", friendId: "Maokai" },
  { champId : "Swain", friendId: "Vladimir" },
  { champId : "Syndra", friendId: "KhaZix" },
  { champId : "Syndra", friendId: "Nami" },
  { champId : "Syndra", friendId: "Teemo" },
  { champId : "Syndra", friendId: "Thresh" },
  { champId : "Syndra", friendId: "Zac" },
  { champId : "Syndra", friendId: "Zilean" },
  { champId : "TahmKench", friendId: "Ashe" },
  { champId : "TahmKench", friendId: "Illaoi" },
  { champId : "TahmKench", friendId: "Kalista" },
  { champId : "TahmKench", friendId: "KogMaw" },
  { champId : "TahmKench", friendId: "Sejuani" },
  { champId : "TahmKench", friendId: "Swain" },
  { champId : "Talon", friendId: "Darius" },
  { champId : "Talon", friendId: "Fizz" },
  { champId : "Talon", friendId: "Ryze" },
  { champId : "Talon", friendId: "Sejuani" },
  { champId : "Talon", friendId: "Sion" },
  { champId : "Talon", friendId: "Zed" },
  { champId : "Taric", friendId: "Caitlyn" },
  { champId : "Taric", friendId: "Draven" },
  { champId : "Taric", friendId: "Ezreal" },
  { champId : "Taric", friendId: "Graves" },
  { champId : "Taric", friendId: "Sivir" },
  { champId : "Taric", friendId: "Vayne" },
  { champId : "Teemo", friendId: "Blitzcrank" },
  { champId : "Teemo", friendId: "Cassiopeia" },
  { champId : "Teemo", friendId: "Jax" },
  { champId : "Teemo", friendId: "LeeSin" },
  { champId : "Teemo", friendId: "Singed" },
  { champId : "Teemo", friendId: "Volibear" },
  { champId : "Thresh", friendId: "Caitlyn" },
  { champId : "Thresh", friendId: "Draven" },
  { champId : "Thresh", friendId: "Ezreal" },
  { champId : "Thresh", friendId: "Jinx" },
  { champId : "Thresh", friendId: "Lucian" },
  { champId : "Thresh", friendId: "Vayne" },
  { champId : "Tristana", friendId: "Alistar" },
  { champId : "Tristana", friendId: "Blitzcrank" },
  { champId : "Tristana", friendId: "Leona" },
  { champId : "Tristana", friendId: "Lulu" },
  { champId : "Tristana", friendId: "Taric" },
  { champId : "Tristana", friendId: "Thresh" },
  { champId : "Trundle", friendId: "Aatrox" },
  { champId : "Trundle", friendId: "Anivia" },
  { champId : "Trundle", friendId: "Darius" },
  { champId : "Trundle", friendId: "JarvanIV" },
  { champId : "Trundle", friendId: "Lissandra" },
  { champId : "Trundle", friendId: "Vayne" },
  { champId : "Tryndamere", friendId: "Aatrox" },
  { champId : "Tryndamere", friendId: "Ashe" },
  { champId : "Tryndamere", friendId: "Kayle" },
  { champId : "Tryndamere", friendId: "Nunu" },
  { champId : "Tryndamere", friendId: "Olaf" },
  { champId : "Tryndamere", friendId: "Zilean" },
  { champId : "TwistedFate", friendId: "Aatrox" },
  { champId : "TwistedFate", friendId: "Gangplank" },
  { champId : "TwistedFate", friendId: "Nocturne" },
  { champId : "TwistedFate", friendId: "Rammus" },
  { champId : "TwistedFate", friendId: "Shen" },
  { champId : "TwistedFate", friendId: "Taric" },
  { champId : "Twitch", friendId: "Blitzcrank" },
  { champId : "Twitch", friendId: "Braum" },
  { champId : "Twitch", friendId: "Leona" },
  { champId : "Twitch", friendId: "Nami" },
  { champId : "Twitch", friendId: "Taric" },
  { champId : "Twitch", friendId: "Thresh" },
  { champId : "Udyr", friendId: "Aatrox" },
  { champId : "Udyr", friendId: "Ahri" },
  { champId : "Udyr", friendId: "Amumu" },
  { champId : "Udyr", friendId: "Janna" },
  { champId : "Udyr", friendId: "LeBlanc" },
  { champId : "Udyr", friendId: "Ryze" },
  { champId : "Urgot", friendId: "Alistar" },
  { champId : "Urgot", friendId: "Blitzcrank" },
  { champId : "Urgot", friendId: "Leona" },
  { champId : "Urgot", friendId: "Soraka" },
  { champId : "Urgot", friendId: "Taric" },
  { champId : "Urgot", friendId: "Thresh" },
  { champId : "Varus", friendId: "Blitzcrank" },
  { champId : "Varus", friendId: "Leona" },
  { champId : "Varus", friendId: "Nami" },
  { champId : "Varus", friendId: "Sona" },
  { champId : "Varus", friendId: "Soraka" },
  { champId : "Varus", friendId: "Thresh" },
  { champId : "Vayne", friendId: "Alistar" },
  { champId : "Vayne", friendId: "Blitzcrank" },
  { champId : "Vayne", friendId: "Leona" },
  { champId : "Vayne", friendId: "Nami" },
  { champId : "Vayne", friendId: "Nunu" },
  { champId : "Vayne", friendId: "Thresh" },
  { champId : "Veigar", friendId: "Amumu" },
  { champId : "Veigar", friendId: "LeBlanc" },
  { champId : "Veigar", friendId: "Lux" },
  { champId : "Veigar", friendId: "Sejuani" },
  { champId : "Veigar", friendId: "Skarner" },
  { champId : "Veigar", friendId: "Warwick" },
  { champId : "Velkoz", friendId: "Aatrox" },
  { champId : "Velkoz", friendId: "Amumu" },
  { champId : "Velkoz", friendId: "Galio" },
  { champId : "Velkoz", friendId: "JarvanIV" },
  { champId : "Velkoz", friendId: "Leona" },
  { champId : "Velkoz", friendId: "Yasuo" },
  { champId : "Vi", friendId: "Caitlyn" },
  { champId : "Vi", friendId: "Heimerdinger" },
  { champId : "Vi", friendId: "Lux" },
  { champId : "Vi", friendId: "Orianna" },
  { champId : "Vi", friendId: "Yasuo" },
  { champId : "Vi", friendId: "Zed" },
  { champId : "Viktor", friendId: "Aatrox" },
  { champId : "Viktor", friendId: "Amumu" },
  { champId : "Viktor", friendId: "ChoGath" },
  { champId : "Viktor", friendId: "JarvanIV" },
  { champId : "Viktor", friendId: "Malzahar" },
  { champId : "Viktor", friendId: "Sona" },
  { champId : "Vladimir", friendId: "Amumu" },
  { champId : "Vladimir", friendId: "JarvanIV" },
  { champId : "Vladimir", friendId: "Kennen" },
  { champId : "Vladimir", friendId: "Maokai" },
  { champId : "Vladimir", friendId: "Swain" },
  { champId : "Vladimir", friendId: "Zed" },
  { champId : "Volibear", friendId: "Ashe" },
  { champId : "Volibear", friendId: "Caitlyn" },
  { champId : "Volibear", friendId: "Fiora" },
  { champId : "Volibear", friendId: "Singed" },
  { champId : "Volibear", friendId: "Teemo" },
  { champId : "Volibear", friendId: "Vayne" },
  { champId : "Warwick", friendId: "Katarina" },
  { champId : "Warwick", friendId: "LeeSin" },
  { champId : "Warwick", friendId: "Lux" },
  { champId : "Warwick", friendId: "Malzahar" },
  { champId : "Warwick", friendId: "Mordekaiser" },
  { champId : "Warwick", friendId: "Veigar" },
  { champId : "Wukong", friendId: "Amumu" },
  { champId : "Wukong", friendId: "Galio" },
  { champId : "Wukong", friendId: "JarvanIV" },
  { champId : "Wukong", friendId: "Katarina" },
  { champId : "Wukong", friendId: "Orianna" },
  { champId : "Wukong", friendId: "Yasuo" },
  { champId : "Xerath", friendId: "Akali" },
  { champId : "Xerath", friendId: "Amumu" },
  { champId : "Xerath", friendId: "Evelynn" },
  { champId : "Xerath", friendId: "JarvanIV" },
  { champId : "Xerath", friendId: "Quinn" },
  { champId : "Xerath", friendId: "Varus" },
  { champId : "XinZhao", friendId: "Blitzcrank" },
  { champId : "XinZhao", friendId: "Garen" },
  { champId : "XinZhao", friendId: "JarvanIV" },
  { champId : "XinZhao", friendId: "KhaZix" },
  { champId : "XinZhao", friendId: "Pantheon" },
  { champId : "XinZhao", friendId: "Yasuo" },
  { champId : "Yasuo", friendId: "Alistar" },
  { champId : "Yasuo", friendId: "ChoGath" },
  { champId : "Yasuo", friendId: "Janna" },
  { champId : "Yasuo", friendId: "Malphite" },
  { champId : "Yasuo", friendId: "Vi" },
  { champId : "Yasuo", friendId: "Wukong" },
  { champId : "Yorick", friendId: "Cassiopeia" },
  { champId : "Yorick", friendId: "Karthus" },
  { champId : "Yorick", friendId: "KogMaw" },
  { champId : "Yorick", friendId: "Mordekaiser" },
  { champId : "Yorick", friendId: "Vayne" },
  { champId : "Yorick", friendId: "Zilean" },
  { champId : "Zac", friendId: "Aatrox" },
  { champId : "Zac", friendId: "Lulu" },
  { champId : "Zac", friendId: "Malphite" },
  { champId : "Zac", friendId: "Orianna" },
  { champId : "Zac", friendId: "Syndra" },
  { champId : "Zac", friendId: "Yasuo" },
  { champId : "Zed", friendId: "Aatrox" },
  { champId : "Zed", friendId: "Nasus" },
  { champId : "Zed", friendId: "Shen" },
  { champId : "Zed", friendId: "Talon" },
  { champId : "Zed", friendId: "Vi" },
  { champId : "Zed", friendId: "Vladimir" },
  { champId : "Ziggs", friendId: "Aatrox" },
  { champId : "Ziggs", friendId: "Amumu" },
  { champId : "Ziggs", friendId: "JarvanIV" },
  { champId : "Ziggs", friendId: "Leona" },
  { champId : "Ziggs", friendId: "Malphite" },
  { champId : "Ziggs", friendId: "Sejuani" },
  { champId : "Zilean", friendId: "Aatrox" },
  { champId : "Zilean", friendId: "Hecarim" },
  { champId : "Zilean", friendId: "Jax" },
  { champId : "Zilean", friendId: "Singed" },
  { champId : "Zilean", friendId: "Syndra" },
  { champId : "Zilean", friendId: "Tryndamere" },
  { champId : "Zyra", friendId: "Amumu" },
  { champId : "Zyra", friendId: "Ashe" },
  { champId : "Zyra", friendId: "Ezreal" },
  { champId : "Zyra", friendId: "MissFortune" },
  { champId : "Zyra", friendId: "Varus" },
  { champId : "Zyra", friendId: "Yasuo" }
];
var test = league.slice();
var test2 = friends.slice();
for (var i = 0; i < test.length; i++) {
  for (var j = 0; j < test2.length; j++) {
    if (test[i]["name"] === test2[j]["champId"]) {
      test2[j]["champId"] = test[i]["champId"];
    }
    if (test[i]["name"] === test2[j]["friendId"]) {
      test2[j]["friendId"] = test[i]["champId"];
    }
  }
};
console.log(test2)
